# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,textfile,process,time
collector:
  service:
    services-where: Name='windows_exporter' or Name='vmtools'
  process:
    whitelist: 'Firefox|Chrome'
  textfile:
    directory: 'C:\Program Files (x86)\windows_exporter\textfile_inputs'
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
  max-requests: 5
