---
# tasks file for win_vmware_provisioning
- name: Deploy Virtual Machine from template Vcenter
  vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ username }}@windows.com.py'
    password: '{{ password }}'
    validate_certs: False
    folder: /FOLDER/vm/{{ vmware_win_folder }}
    template: '{{ vmware_win_template }}'
    resource_pool: '{{ vmware_win_resource_pool }}'
    datacenter: '{{ vmware_datacenter }}'
    cluster: '{{ vmware_cluster }}'
    name: '{{ vmware_env }}-{{ vmware_win_os }}-{{ inventory_hostname.replace((vmware_host_env),"").split(".")[0] | upper }}'
    state: present
    hardware:
      memory_mb: '{{ vmware_hw_memory_mb }}'
      num_cpus: '{{ vmware_hw_num_cpus }}'
      num_cpu_cores_per_socket: '{{ vmware_hw_num_cpu_cores_per_socket }}'
      hotadd_cpu: '{{ vmware_hw_hotadd_cpu }}'
      hotadd_memory: '{{ vmware_hw_hotadd_memory }}'
    networks:
      - name: '{{ vmware_nw_name }}'
        ip: '{{ ansible_host }}'
        netmask: '{{ vmware_nw_netmask }}'
        gateway: '{{ vmware_nw_gateway }}'
    wait_for_ip_address: True
    customization:
      hostname: '{{ inventory_hostname }}'
      dns_servers:
        - ip.x.x.x
        - ip.x.x.y
      password: '{{ local_admin_pass }}'
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  delegate_to: localhost

- name: "Wait for port 5585 to become open on the host, don't start checking for 10 seconds"
  wait_for_connection:
    delay: 120
    timeout: 600

- name: Unir servidor al dominio WINDOWS
  win_domain_membership:
    dns_domain_name: windows.com.py
    hostname: '{{ inventory_hostname }}'
    domain_admin_user: '{{ username }}@windows.com.py'
    domain_admin_password: '{{ password }}'
    domain_ou_path: "OU=Server,DC=windows,DC=com,DC=py"
    state: domain
  throttle: 1
  register: domain_state
  until: domain_state.failed == false
  retries: 3
  delay: 5

- name: Reiniciar el servidor
  win_reboot:
    post_reboot_delay: 20
  when: domain_state.reboot_required

